Verify that the file exists

diff --git a/bin/moodle-compose b/bin/moodle-compose
--- a/bin/moodle-compose
+++ b/bin/moodle-compose
@@ -100,6 +100,10 @@ if [ -n "$1" ]; then
         else
 	        dump=$2
         fi
+        if [ ! -f $dump ]; then
+          >&2  printf "\n>> File $dump not found\n\n"
+          exit 1
+        fi
         clear
         printf "\n>>> Removing the Moodle DB\n\n"
         moodle-compose exec -T db /usr/bin/dropdb -e -U moodle moodle
